-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "ratePerKm" DOUBLE PRECISION NOT NULL DEFAULT 0.0;

-- AlterTable
ALTER TABLE "Trip" ADD COLUMN     "distanceInKm" DOUBLE PRECISION,
ADD COLUMN     "tenantBilling" DOUBLE PRECISION,
ADD COLUMN     "vendorCost" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Vendor" ADD COLUMN     "ratePerKm" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
